

export const carouselTwo = [
  {
    "backgroundImage": '/images/Talwinder.jpg',
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "bg-primary",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage":"images/Party.JPG",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage":"images/Diljit.JPG",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Clubbing.JPG",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/AP.PNG",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Festival.JPG",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Drake.PNG",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Weeknd.PNG",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#96f",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Dj.JPG",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Metro-Spider.webp",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Heroes-Villains.jpeg",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/FourYou.jpeg",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage":"images/shubh.jpeg",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/ClubbingTwo.JPG",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage":"images/JohnMayer.webp",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/SZA.png",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage":"images/Tomorrowland.jpeg",
    "logoVisible": true,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": true,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": true,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  }
]
