

export const carousel = [
  {
    "backgroundImage": '/images/Talwinder.jpg',
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "bg-primary",
    "isSongVisible": true,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  
  {
    "backgroundImage":"images/Diljit.JPG",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Clubbing.JPG",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/AP.PNG",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Festival.JPG",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Drake.PNG",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Weeknd.PNG",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#96f",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Dj.JPG",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  }
]

export const carouselOne = [
  
  
  {
    "backgroundImage": "images/Metro-Spider.webp",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Heroes-Villains.jpeg",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/FourYou.jpeg",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage":"images/shubh.jpeg",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/ClubbingTwo.JPG",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage":"images/JohnMayer.webp",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/SZA.png",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage":"images/Tomorrowland.jpeg",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  }
]


export const carouselTwo = [
  {
    "backgroundImage": '/images/bk.jpeg',
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "bg-primary",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage":"images/Bilal.jpeg",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage":"images/Shinda.JPG",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Travis.webp",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/justinconcert.jpeg",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/partycrod.jpeg",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Obsessed.jpg",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/samsmith.jpeg",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#96f",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  }
  
]
export const carousel_two = [
  {
    "backgroundImage": "images/Trappraa.JPEG",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Gurinder.jpeg",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/Bruno.jpeg",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/brownmunde.jpeg",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage":"images/beauty.png",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/dua.webp",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage":"images/prophec.jpeg",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  },
  {
    "backgroundImage": "images/ari.webp",
    "logoVisible": false,
    "logoIcon": 1,
    "logoBackground": "#ffffff",
    "isSongVisible": false,
    "songName": "chosen",
    "songArtistName": "Bixst,Ty Dolla $ign",
    "songArtistImage": "https://www.beatmatch.app/static/media/highlights-blxst-chosen.ebb29c5925e63dd2a7f3.jpeg",
    "isGenreVisible": false,
    "genre": "EDM",
    "isArtistTopVisible": false,
    "isArtistBottomVisible": false,
    "artistImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg",
    "isFestVisible": false,
    "festTag": "Festival",
    "festImage": "https://www.beatmatch.app/static/media/highlights-kaytranada-2.a9f5a105a7868bcdc036.jpeg"
  }
]
